2018-06-26 11:42:42,158 [Thread-1    ] [INFO ] [django.server       ]  "GET / HTTP/1.1" 200 5171
2018-06-26 11:42:42,228 [Thread-4    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
2018-06-26 11:42:42,232 [Thread-5    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
2018-06-26 11:42:42,233 [Thread-6    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
2018-06-26 11:42:42,242 [Thread-8    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
2018-06-26 11:42:42,246 [Thread-3    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121200
2018-06-26 11:42:42,255 [Thread-9    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1735
2018-06-26 11:42:42,290 [Thread-12   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1262
2018-06-26 11:42:42,291 [Thread-7    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 200 86927
2018-06-26 11:42:42,296 [Thread-10   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 37045
2018-06-26 11:42:42,310 [Thread-11   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
2018-06-26 11:42:42,340 [Thread-13   ] [INFO ] [django.server       ]  "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
2018-06-26 11:42:42,777 [Thread-14   ] [WARNI] [django.request      ]  Not Found: /favicon.ico
2018-06-26 11:42:42,778 [Thread-14   ] [WARNI] [django.server       ]  "GET /favicon.ico HTTP/1.1" 404 3273
2018-06-26 11:42:43,746 [Thread-15   ] [INFO ] [django.server       ]  "GET /match/ HTTP/1.1" 200 9186
2018-06-26 11:43:17,256 [Thread-16   ] [INFO ] [django.server       ]  "POST /match/ HTTP/1.1" 201 9424
2018-06-26 11:43:44,178 [Thread-17   ] [INFO ] [django.server       ]  "POST /match/ HTTP/1.1" 201 9416
2018-06-26 11:44:17,996 [Thread-18   ] [INFO ] [django.server       ]  "POST /match/ HTTP/1.1" 201 9422
2018-06-26 11:44:19,883 [Thread-19   ] [INFO ] [django.server       ]  "GET /match/ HTTP/1.1" 200 9865
2018-06-26 11:48:28,870 [Thread-1    ] [INFO ] [django.server       ]  "GET /get_all_match HTTP/1.1" 200 5882
2018-06-26 12:09:21,227 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_all_match/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/match_ms/match_app/views.py", line 28, in get_all_match
    'team_a': one_match.team_a_id,
AttributeError: 'collections.OrderedDict' object has no attribute 'team_a_id'
2018-06-26 12:09:21,262 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_all_match/ HTTP/1.1" 500 15346
2018-06-26 12:15:00,007 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_all_match/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/match_ms/match_app/views.py", line 28, in get_all_match
    'team_a': one_match.team_a_id,
AttributeError: 'collections.OrderedDict' object has no attribute 'team_a_id'
2018-06-26 12:15:00,024 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_all_match/ HTTP/1.1" 500 15346
2018-06-26 12:16:14,432 [Thread-3    ] [ERROR] [django.request      ]  Internal Server Error: /get_all_match/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/match_ms/match_app/views.py", line 28, in get_all_match
    'team_a': one_match.team_a_id,
AttributeError: 'collections.OrderedDict' object has no attribute 'team_a_id'
2018-06-26 12:16:14,447 [Thread-3    ] [ERROR] [django.server       ]  "GET /get_all_match/ HTTP/1.1" 500 15346
2018-06-26 12:18:01,438 [Thread-4    ] [ERROR] [django.request      ]  Internal Server Error: /get_all_match/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/match_ms/match_app/views.py", line 28, in get_all_match
    'team_a': one_match.team_a_id,
AttributeError: 'collections.OrderedDict' object has no attribute 'team_a_id'
2018-06-26 12:18:01,473 [Thread-4    ] [ERROR] [django.server       ]  "GET /get_all_match/ HTTP/1.1" 500 15346
2018-06-26 12:19:43,892 [Thread-5    ] [ERROR] [django.request      ]  Internal Server Error: /get_all_match/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/match_ms/match_app/views.py", line 28, in get_all_match
    'team_a': one_match.team_a_id,
AttributeError: 'collections.OrderedDict' object has no attribute 'team_a_id'
2018-06-26 12:19:43,933 [Thread-5    ] [ERROR] [django.server       ]  "GET /get_all_match/ HTTP/1.1" 500 15346
2018-06-26 12:20:14,760 [Thread-6    ] [ERROR] [django.request      ]  Internal Server Error: /get_all_match/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/match_ms/match_app/views.py", line 28, in get_all_match
    'team_a': one_match.team_a_id,
AttributeError: 'collections.OrderedDict' object has no attribute 'team_a_id'
2018-06-26 12:20:14,778 [Thread-6    ] [ERROR] [django.server       ]  "GET /get_all_match/ HTTP/1.1" 500 15346
2018-06-26 12:21:30,841 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_all_match/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/match_ms/match_app/views.py", line 35, in get_all_match
    url_req.urlopen(MSUrls.team + 'get_match_team/', data=data).read()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
2018-06-26 12:21:30,874 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_all_match/ HTTP/1.1" 500 16403
2018-06-26 12:21:40,964 [Thread-3    ] [ERROR] [django.request      ]  Internal Server Error: /get_all_match/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/match_ms/match_app/views.py", line 35, in get_all_match
    url_req.urlopen(MSUrls.team + 'get_match_team/', data=data).read()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
2018-06-26 12:21:40,995 [Thread-3    ] [ERROR] [django.server       ]  "GET /get_all_match/ HTTP/1.1" 500 16403
2018-06-26 12:23:03,529 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_all_match/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/match_ms/match_app/views.py", line 35, in get_all_match
    url_req.urlopen(MSUrls.team + 'get_match_team/', data=data).read()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
2018-06-26 12:23:03,551 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_all_match/ HTTP/1.1" 500 16403
2018-06-26 12:23:50,903 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_all_match/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/match_ms/match_app/views.py", line 35, in get_all_match
    url_req.urlopen(MSUrls.team + 'get_match_team/', data=data).read()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
2018-06-26 12:23:50,925 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_all_match/ HTTP/1.1" 500 16403
2018-06-26 12:24:26,747 [Thread-3    ] [ERROR] [django.request      ]  Internal Server Error: /get_all_match/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/match_ms/match_app/views.py", line 35, in get_all_match
    url_req.urlopen(MSUrls.team + 'get_match_team/', data=data).read()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
2018-06-26 12:24:26,764 [Thread-3    ] [ERROR] [django.server       ]  "GET /get_all_match/ HTTP/1.1" 500 16403
2018-06-26 12:25:15,243 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_all_match/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/match_ms/match_app/views.py", line 35, in get_all_match
    url_req.urlopen(MSUrls.team + 'get_match_team/', data=data).read()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
2018-06-26 12:25:15,264 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_all_match/ HTTP/1.1" 500 16403
2018-06-26 12:25:25,498 [Thread-3    ] [ERROR] [django.request      ]  Internal Server Error: /get_all_match/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/match_ms/match_app/views.py", line 35, in get_all_match
    url_req.urlopen(MSUrls.team + 'get_match_team/', data=data).read()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
2018-06-26 12:25:25,530 [Thread-3    ] [ERROR] [django.server       ]  "GET /get_all_match/ HTTP/1.1" 500 16403
2018-06-26 12:27:36,756 [Thread-1    ] [INFO ] [django.server       ]  "GET / HTTP/1.1" 200 5171
2018-06-26 12:27:43,942 [Thread-8    ] [ERROR] [django.request      ]  Internal Server Error: /get_all_match/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/match_ms/match_app/views.py", line 38, in get_all_match
    url_req.urlopen(MSUrls.team + 'get_match_team/', data=data).read()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
2018-06-26 12:27:43,963 [Thread-8    ] [ERROR] [django.server       ]  "GET /get_all_match/ HTTP/1.1" 500 16403
2018-06-26 12:28:30,168 [Thread-1    ] [ERROR] [django.request      ]  Internal Server Error: /get_all_match/
Traceback (most recent call last):
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/env_worldcup/lib/python3.6/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/Users/nonstopio/workspace/microservices/worldcup/match_ms/match_app/views.py", line 38, in get_all_match
    url_req.urlopen(MSUrls.team + 'get_match_team/', data=data).read()
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
2018-06-26 12:28:30,211 [Thread-1    ] [ERROR] [django.server       ]  "GET /get_all_match/ HTTP/1.1" 500 16403
2018-06-26 12:28:43,464 [Thread-1    ] [INFO ] [django.server       ]  "GET /get_all_match/ HTTP/1.1" 200 888
2018-06-26 12:45:52,901 [Thread-1    ] [INFO ] [django.server       ]  "GET /get_all_match HTTP/1.1" 200 7410
2018-06-26 14:36:17,037 [Thread-1    ] [INFO ] [django.server       ]  "GET /match/ HTTP/1.1" 200 9865
2018-06-26 14:36:17,067 [Thread-7    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 304 0
2018-06-26 14:36:17,067 [Thread-3    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
2018-06-26 14:36:17,068 [Thread-5    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
2018-06-26 14:36:17,068 [Thread-6    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
2018-06-26 14:36:17,068 [Thread-8    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
2018-06-26 14:36:17,068 [Thread-4    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
2018-06-26 14:36:17,075 [Thread-9    ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
2018-06-26 14:36:17,081 [Thread-12   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
2018-06-26 14:36:17,081 [Thread-11   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
2018-06-26 14:36:17,081 [Thread-10   ] [INFO ] [django.server       ]  "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
2018-06-26 14:36:17,166 [Thread-13   ] [INFO ] [django.server       ]  "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
2018-06-26 14:36:31,968 [Thread-14   ] [INFO ] [django.server       ]  "GET /match/ HTTP/1.1" 200 9865
2018-06-26 14:39:44,078 [Thread-20   ] [INFO ] [django.server       ]  "GET /match/ HTTP/1.1" 200 9865
2018-06-26 14:41:42,125 [Thread-26   ] [INFO ] [django.server       ]  "GET /match/ HTTP/1.1" 200 9865
2018-06-26 14:41:43,812 [Thread-27   ] [INFO ] [django.server       ]  "GET /match/ HTTP/1.1" 200 9865
2018-06-26 14:44:37,623 [Thread-33   ] [INFO ] [django.server       ]  "GET /match/ HTTP/1.1" 200 9865
2018-06-26 14:44:44,809 [Thread-34   ] [INFO ] [django.server       ]  "GET /match/ HTTP/1.1" 200 9865
2018-06-26 14:46:28,767 [Thread-40   ] [INFO ] [django.server       ]  "GET /match/ HTTP/1.1" 200 9865
2018-06-26 14:51:23,406 [Thread-1    ] [INFO ] [django.server       ]  "GET /match/ HTTP/1.1" 200 9865
2018-06-26 14:51:23,456 [Thread-4    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
2018-06-26 14:51:23,457 [Thread-5    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
2018-06-26 14:51:23,469 [Thread-3    ] [INFO ] [django.server       ]  "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121200
2018-06-26 14:52:05,852 [Thread-6    ] [INFO ] [django.server       ]  "GET /match/ HTTP/1.1" 200 9865
2018-06-26 14:52:20,214 [Thread-12   ] [INFO ] [django.server       ]  "GET /match/ HTTP/1.1" 200 9865
2018-06-26 14:52:35,583 [Thread-18   ] [INFO ] [django.server       ]  "GET /match/ HTTP/1.1" 200 9865
2018-06-26 14:56:20,783 [Thread-24   ] [INFO ] [django.server       ]  "GET /match/ HTTP/1.1" 200 9865
2018-06-26 14:56:26,854 [Thread-25   ] [INFO ] [django.server       ]  "GET /match/ HTTP/1.1" 200 9865
2018-06-26 14:56:33,060 [Thread-30   ] [INFO ] [django.server       ]  "GET /match/ HTTP/1.1" 200 9865
